name: Build And Deploy

on:
  push:
    branches: [ long-master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: WorldGuardExtraFlags Jar
      uses: actions/upload-artifact@v2
      with:
        name: WorldGuardExtraFlags Jar
        path: "${{ github.workspace }}/Spigot/target/WorldGuardExtraFlags.jar"
